### ISSUE TITLE
Loot Sheet - Changes are lost

### ISSUE THREAD

**Issue by jocolamarco** [jopeek/fvtt-loot-sheet-npc-5e#134]
Foundryvtt version: 0.7.9
loot-sheet version: 2.5.1
sheet-type: Loot

Issue:
1-Renamed and added more items.
2-Changed permissions to all players from view to edit
3-Went to setup and logged in again as GM
4-Changes from step 1 are missing

**Comment by trioderegion** [comment]
Coming here to comment on the same issue, to hopefully expand on the initial bug report.

1) Create a new loot sheet actor in the sidebar
2) Make this actor's prototype token "unlinked"
3) Ensure that the permissions are default (i.e. "None")
4) Place blank loot actor on the canvas
5) Populate with items
6) Change permissions to "Owner" or "Observer" on the unlinked token's sheet
7) Refresh foundry (F5 or logout/login)
8) Observe all items on the unlinked token are now gone.

**Comment by TomChristoffer** [comment]
Can confirm that this happens both on 0.7 and 0.8, and that it happens specifically when you toggle the permissions on a loot token.

**Comment by lostinlinux** [comment]
Can also confirm this issue on 0.8. I have lost so many hours of work going back and repopulating loot sheets, so I'm glad I at least now know that it's caused by changing the permissions. I can also confirm that it wipes out any currency changes made as well, completely reverting it to the state of the prototype token.
