### ISSUE TITLE
Update for 0.8.9?

### ISSUE THREAD

**Issue by Verthiss** [jopeek/fvtt-loot-sheet-npc-5e#180]
So, I love this mod and prepared tons of stuff in my upcoming campaign around it but when I started testing, it seems to me that a lot of stuff is broken:
1. First and foremost, looting works fine, but when a player tries to move an item to a chest (loot sheet token created to serve as a stash), it copies the item instead of moving it.
2. something weird keeps happening with currencies, looks like loot sheet currency system is different from the one used by a default character sheet? I think I've read that Foundry changed its' currency system but loot sheet stayed the same?
3. There seems to be no option to sell loot. I covered that a little in one of the other issue topics.

So, my question is, is there any hope to get updates on this mod? Because, again, I love it and don't want the campaign without it? ;)

**Comment by PawLoh23** [comment]
Agreed. Currency seems to be glitched rn with the new 5e update today

**Comment by Cynicide** [comment]
I wouldn't suggest people attempt this change as I've hosed the coin in my loot sheet a few times doing this.

There were a lot of changes in dnd5e to allow for currency localization, I suspect this has caused some issues. 

By editing Lines 121 and 153 in npc-sheet.html  from `<label>{{ lookup ../config.currencies i }}:</label>` to `<label>{{lookup (lookup ../config.currencies i) "label"}}:</label>` I was able to get the currency labels back into the sheet. However the split isn't working yet, it just doesn't display any values.

Getting into lootsheetnpc5e.js I changed 1429 - 1435 from:

```
        const conversionRates = { 
            "pp": 1,
            "gp": CONFIG.DND5E.currencyConversion.gp.each, 
            "ep": CONFIG.DND5E.currencyConversion.ep.each,
            "sp": CONFIG.DND5E.currencyConversion.sp.each,
            "cp": CONFIG.DND5E.currencyConversion.cp.each
        }; 
```

to

```
        const conversionRates = { 
            "pp": 1,
            "gp": CONFIG.DND5E.currencies.gp.conversion.each, 
            "ep": CONFIG.DND5E.currencies.ep.conversion.each,
            "sp": CONFIG.DND5E.currencies.sp.conversion.each,
            "cp": CONFIG.DND5E.currencies.cp.conversion.each
        };
```

This hasn't made a difference but I suspect it's required as the old methods seem to have been replaced in dnd5e. I don't have this working yet but I thought I'd share what I've found in case anyone else has any ideas.

I suspect the issue lies with how the .js files does the currencySplit and how it populates c.value on line 122 of the html, but I might not be a strong enough programmer to figure it out.

**Comment by Cynicide** [comment]
It turns out that the currencySplit that was loaded when the sheet is opened or changed is the only one not using `currencysplit[c].value`. I'm not sure why. 

I've done some limited testing on my world and things seem OK, I'm not using all the features of the mod though so this should be checked before merging. I've created this PR.

#181 

If you want to test yourself my fork is here: [https://github.com/Cynicide/fvtt-loot-sheet-npc-5e](url) Please please please backup your world before trying this. JS is not my primary language, I just wanted to get this up and going so I could prep for my game on Tuesday.

**Comment by AsianDumpring** [comment]
Also experiencing this same bug. Tanked my game mid-session when the party realized all their loot was bunked. Oops.
