### ISSUE TITLE
Still getting "No active DM on the scene"

### ISSUE THREAD

**Issue by ctbritt** [jopeek/fvtt-loot-sheet-npc-5e#205]
**Describe the bug**
Players can't interact with sheet because it still says no active DM is on the scene. 

**To Reproduce**
1. Drop loot token. 
2. Players double click
3. No looting allowed. 
4. Red error message 

**Expected behavior**
Players should be able to loot the sheet

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 3.2.5

**Additional context**
All modules EXCEPT Loot Sheet are disabled.

**Comment by DanielBoettner** [comment]
* What means "still" was their an issue before?
* Which Foundry Version do you use? The module AFAIK needs Foundry Version 0.8.x (update to 0.9 will follow)
* When you open the sheet as a GM after dropping a token, are the permissions set on observer - "eye"?
* How is Foundry hosted/run (local on the mac, dedicated server/...) ?

In my local dev environment I only sporadically encountered this error when I used several browsers.
Had to make sure to go back to the GM window to let foundry know the GM is active in that scene.

_Also you may want to wait a day until we changed to foundry listing to pick up the new master with version 3.3.81.
Not sure if this actually solves the issue. But the new master is a huge refactoring/rewrite of the module. So please test again with that version as soon as it is available via FoundryVTT modules listing or use https://raw.githubusercontent.com/jopeek/fvtt-loot-sheet-npc-5e/master/module.json to install it manually._

The new version also comes with 2 pre packed Macros in a compendium. These macros allow updating permissions on a token/on several tokens.

![image](https://user-images.githubusercontent.com/21986545/147096091-6ef5a89c-9d4d-4513-9b3d-0eb57f6cb18e.png)

-----

What happens if you open the dev console in chrome while using foundry and paste the following code?

```js
game.users.forEach((u) => {
            if (u.isGM && u.active && u.viewedScene === game.user.viewedScene) {
                targetGM = u;
            }
        });
```

It should result in something like

![image](https://user-images.githubusercontent.com/21986545/147095048-2fe6f4ed-0978-4efe-ad78-449d2e7d8fd2.png)

Its normal that targetGM would be undefined first but has a value when you type it afterwards.

**Comment by ctbritt** [comment]
Thanks very much for your thoughtful reply! When i paste that code, I just get "undefined" and nothing else.

**Comment by DanielBoettner** [comment]
@ctbritt could you test the latest version of the module?

I really would like to fix this if possible.

With the marcos from my first reply.
And players active the sheet should look (mostly) like this when you open it.

* drop a token on the map* 
* add some loot manually / lootpopulator / per GM sidebar.
* Have an encounter or let players meet the ncp.
* decide to make NPC lootable.
* use the macro while having the token selected.
* should have a chest symbol over the token now
* in the sheet the players should all have an eye symbol (observer permissions) so they can loot/buy

![image](https://user-images.githubusercontent.com/21986545/147367186-7dae452c-6e70-4c42-8864-d6ce61b4d9a0.png)

**Comment by DanielBoettner** [comment]
@ctbritt could you test this in your console?

```js
targetGM = game.users.filter((u) => {
            return u.isGM && u.active && u.viewedScene === game.user.viewedScene
        });

targetGM?.[0] || false;
```

* running it as a gm it should **always** return a User
* running as a player/user 
  * when in the same scene it should return the user
  * when in a different scene it should return false
  
In the attached Screenshot you see GM to the left and player to the right
 
![image](https://user-images.githubusercontent.com/21986545/147847474-4368f30f-7c28-479a-81cb-f813ad9c19f5.png)

**Comment by ctbritt** [comment]
Hi, I've updated to the latest version -- I'm on 3.4.1 and foundry v9.238 -- with only LootSheet and Find the Culprit modules enabled. 

As GM I can open the token I've set to open in a loot sheet, but I still can't bulk change permissions. I have to do it one by one, which involves clicking, opening the window again, clicking, etc. 

As a player logged into the same scene, when I double-click the token, just the basic DnD5e sheet opens up. It's not a loot sheet document.

When I paste your macro into the console, in the GM window, I get a user object returned. When I paste it in the window where I'm logged in as a player, I get "false" returned.

I'm at a bit of a loss on this.

**Comment by ctbritt** [comment]
So, i've updated to lootsheet v3.4.2.7, and I'm still getting the "no GM on this scene" error.

**Comment by DanielBoettner** [comment]
@ctbritt thanks for testing.

If you can, please try to get hold of me on the FoundryVTT discord message me directly.
Would like to debug this with you.

The linked branch will bring fixes and optimizations for permissions again.
The GM issues still is weird.

A thing I almost always have to to while testing looting with the sheet.
Is to reload both windows. And make sure to click into the canvas /map for the gm.
Otherwise the missing GM info will popup.
With two Screens it could look like this.

Not quite sure if both windows have to be "not minimized" or other things that might influence the status of a user beeing in a scene.

![image](https://user-images.githubusercontent.com/21986545/147873432-92ede5d3-a843-4070-9c39-faaa78ba6b93.png)

In the UI it should look like this. When both the GM and the user are in the same scene.

![image](https://user-images.githubusercontent.com/21986545/147873481-856b28b8-1614-4487-a8ad-67898f78578c.png)
