### ISSUE TITLE
Manually increase/refresh merchant inventory?

### ISSUE THREAD

**Issue by unsoluble** [jopeek/fvtt-loot-sheet-npc-5e#23]
Much like you can manually increase the cost of a merchant's items, would be great to also be able to manually increase/refresh the quantity (after a rather spendy adventuring party comes through and wipes the place out, say).

Been thinking through the implementation details, and don't really have a great answer for what'd be best re adding uniformly to all items, versus setting a max for each and then topping up, versus... I dunno. Worth throwing on the whiteboard at least, I think. :)

**Comment by KageJittai** [comment]
This honestly might be solvable with the roll tables feature. Since that allows you to "restock" a shop.

Additionally, if you have your shop set up as an actor, players only buy from tokens. So you could just replace the current token with a new token for the actor. This will make a new copy of all the original actor's contents.

The second method is also good for shops in different locations. For example if you have a "General Shop" or "Tavern Owner" actor, you can copies of that shop on to multiple scenes.

**Comment by unsoluble** [comment]
Oh man, didn’t even think about the fact that the inventory is tied to the *token instance*. That’s going to help immensely, thanks!
