### ISSUE TITLE
[bug][v9] Actors with Loot Sheet assigned do not show loot sheet when double-clicked; remain default sheet instead.

### ISSUE THREAD

**Issue by Janner3D** [jopeek/fvtt-loot-sheet-npc-5e#235]
**Describe the bug**
When an actor is assigned the NPC Loot Sheet 5e as their character sheet, the sheet fails to open to the appropriate sheet when clicked.

**To Reproduce**
1. Go to 'Sheet'
2. Assign 'this sheet' to NPC Loot Sheet 5e
3. Save Configuration
4. Reopen actor's sheet.

**Expected behavior**
The actor's sheet should be the assigned loot sheet. Instead, it defaults to the Default Sheet.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Additional context**

![image](https://user-images.githubusercontent.com/35965176/147863832-0a4df4c9-968b-4e24-880f-d38124c59ea1.png)

**Comment by gcolgate** [comment]
I have a fix for this .... if DanielBoetnerr has not fixed this. 

Describe the bug
In 9.242, somehow (maybe because other modules) no loot sheets worked. I managed to fix them by sanitizing inputs.

My loot actors had incorrect currency. They were old actor first created in 8. something, but new ones did not work either. You could not click on the actor or the token to bring up the loot sheet, it would spew an error.

Here is the fix, I added an IF statement inside convertCurrencyFromObject to fix it.
Perhaps there is another better fix.

Line 45 of LootHseetNPC5eHelper.js
/**
* Handles Currency from currency.TYPE.value to currency.TYPE for backwords support
* @param {string} folderPath - The directory to loop through
*/
static convertCurrencyFromObject(currency) {
// fix for broken case
Object.entries(currency).map(([key, value]) => {
if (value) {
currency[key] = value.value ?? value;
} else { currency[key] = 0; }
});
return currency;
}

**Comment by DanielBoettner** [comment]
Please test https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/nightly-v3.4.5.8
