### ISSUE TITLE
[Merchant] I get two copies when buying an item.

### ISSUE THREAD

**Issue by Allmight** [jopeek/fvtt-loot-sheet-npc-5e#258]
**Describe the bug**
When i buy items from a merchant that have a higher quantity, say 10+, i get two of the same item in my inventory for the price of one.

**To Reproduce**
1. Set the quantity for the item, for example a dagger, to 10 or more.
2. Now buy that item from the merchant with a player character.
3. Should be charged for one item but get two. Even shows up as bought twice in chat.

**Expected behavior**
I should only recieve one item instead of two.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: nightly-3.4.5.8
 - Foundry Version: v9 b245
 - D&D Version: 1.5.7

**Additional context**
I have tried this with different categories of items, but mostly weapons. Same result no matter what type of item used.
I have tried several nightly builds, same problem in all of them. Pre-Nightly builds does not work at all for me, but saw that is a known problem.

NOTE: I have all modules disabled, just Loot Sheet NPC 5e is enabled.

**Comment by Noracto** [comment]
I seem to have the same problem just from general looting.

**Describe the bug**
When Looting from dead bodies (Tested Goblins and Hobgoblins in 5e) Items that are looted are doubled in players inventory.

**To Reproduce**
Steps to reproduce the behavior:

1. Set dead npc sheet to lootsheet
2. loot all items

**Expected behavior**
I should only recieve one item instead of two.

**Desktop (please complete the following information):**

OS: Windows 10
Browser: Edge
Version: nightly-3.4.5.8
Foundry Version: v9 b245
D&D Version: 1.5.7

**Additional context**
Only tried with weapons so far

**Comment by DanielBoettner** [comment]
Please test if this problem is still occurring in https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/v3.5.8

**Comment by davidhawbecker** [comment]
I appear to be having the same issue.  No matter what I set the fallbacks to it auto-seeds two of the same items whenever I drop a token on the scene.  

All of my software is current as of today, Foundry, Game System and Modules.

**Comment by DanielBoettner** [comment]
> I appear to be having the same issue. No matter what I set the fallbacks to it auto-seeds two of the same items whenever I drop a token on the scene.

What you describe is a different thing as the issue above.

This issue describes that when an actor (player or gm) buys from an NPC the item was duplicated.

The seeding is something different. And you problem is likely related to default values or a setting in the sheet or the rolltable.
