### ISSUE TITLE
[Feature request(s)]: Dark mode default setting, auto-lootable dead tokens and chat log

### ISSUE THREAD

**Issue by GabrielOsvair** [jopeek/fvtt-loot-sheet-npc-5e#275]
(Google Translator) Some updates that I would find interesting, would be the existence of a general setting for dark mode (avoid activating on each sheet). Another issue would be that there was a trigger for dead characters (using the CUB module or something) to be automatically converted into lootable tokens. Finally, the option to send a message in the chat when we add items to the sheet (optional).

**Comment by DanielBoettner** [comment]
>  send a message in the chat when we add items to the sheet 

What kind of info are you thinking of? A general info that some loot was added is likely possible. 
More detailed could be messy very fast. 

> dark mode default

Reasonable. Will add a setting for that.

>  Another issue would be that there was a trigger for dead characters (using the CUB module or something) to be automatically converted into lootable tokens

I think other modules should handle that kind of logic. The sheet offers an API that does the same thing as the interface button or the macros (see compendium). Modules like CUB could add a call to the sheet to convert the tokens at the end of an encounter.

Handling this logic in the sheet would cause a lot of work because of all the different ways people might want that to happen. Some one dead chars dot be lootable right away, other might want it to happen when the encounter ends, ...

**Comment by GabrielOsvair** [comment]
Perhaps displaying a message with the added items and coins would be interesting, but there should be a way to disable this setting as it might get annoying with time (it's not urgent or necessary).

Regarding the automation of the conversion of dead actors sheets, would it be interesting to request the feature on the CUB page?

**Comment by DanielBoettner** [comment]
Either CUB or any other module really that would handle an encounter.
Maybe consider asking around at the FoundryVTT discord #module-discussions which modules would be interesting.

Regarding the chat messages. I honestly found it to be annoying even having ui notifications every time.
I think most of the times would just add more clicks to delete all the messages you don't need and want anymore.

The dark mode (default) setting will come soon.
