### ISSUE TITLE
Was the price modifier removed?

### ISSUE THREAD

**Issue by Nedrapter** [jopeek/fvtt-loot-sheet-npc-5e#297]
Not exactly a bug, but that featured was extremely convenient. I can't it anymore, is it removed or placed somewhere not very visible?

**Comment by DanielBoettner** [comment]
You mean in the trade tab?
A GM can have a active character as well if he so wishes.

If the character has funds he can do the same interactions as a player could do.

**Comment by MSdaW** [comment]
> Edit: Found it. Was hard to notice once you start scrolling. Why does it ask for assigned actor now though? As the DM I wouldn't have an assigned actor.

Hi, could you tell me were you found it? Thank you

**Comment by MSdaW** [comment]
Hi. found a math problem with the price modifier. If you set the price modifier to 200%, the prices will be doubled. When you buy an item, the purchase price (which has already been doubled) is also doubled. This means that if the price increases by 100%, the price will be quadrupled instead of doubled.

Would it be possible to introduce a custom price modifier for selling (PC to NPC) items.
By from Merchant: 120%
Sell to Merchant: 70%
of the price from the SRD
