### ISSUE TITLE
No DND 5E Loot sheet as a option in the sheet dropdown.

### ISSUE THREAD

**Issue by hematic** [jopeek/fvtt-loot-sheet-npc-5e#305]
Module Version : 3.5.9
FoundryVTT Version : v9 Build 249
DND 5e System Version : 1.5.7

With the module installed and activated, no option exists in the dropdown to specify the right sheet type.
![image](https://user-images.githubusercontent.com/7807586/155005637-3edcda2e-dbe5-42bd-b9fd-28da6b934eed.png)

![image](https://user-images.githubusercontent.com/7807586/155005747-e7619118-06a0-4318-abeb-960accadbb8c.png)

Not really sure what other information tro provide, the core functionality just appears to be missing entirely.

**Comment by DanielBoettner** [comment]
Any errors in the console?

Hit F12 on the keyboard and look out for red messages in the new windows console section.

**Comment by hematic** [comment]
Nope.

![image](https://user-images.githubusercontent.com/7807586/155211286-6506473a-eeec-4d25-a337-bab57c25739f.png)

**Comment by hematic** [comment]
Actually, if i scroll ot the very top there is one.

![image](https://user-images.githubusercontent.com/7807586/155211477-d0a4a132-038f-4dd1-8579-3e48b518fc49.png)

**Comment by hematic** [comment]
That file is present at that exact full path. I have attached it here
[npc.js.txt](https://github.com/jopeek/fvtt-loot-sheet-npc-5e/files/8119877/npc.js.txt)
.

**Comment by hematic** [comment]
Also this error.

![image](https://user-images.githubusercontent.com/7807586/155211983-1dadd956-fec5-434c-9867-de4685ccbcaf.png)

**Comment by DanielBoettner** [comment]
First error looks like you might be missing the dnd5e system module.

The second error if caused by a different module.

**Comment by hematic** [comment]
My original post shows the version of the dnd system installed.
DND 5e System Version : 1.5.7

**Comment by DanielBoettner** [comment]
can you check the 404 error than? 
The error is dnd5e related. It doesn't find something it is looking for.
Maybe a migration went wrong or is missing.

I recommend trying to get rid of that error. So far, non of the errors shows relation to the lootsheet.
First error is a dnd 5e system related 404 (something was not found) error while it tries to load npc.js.

Second is a bug in turnmarker. Failing to delete a tile.

**Comment by hematic** [comment]
![image](https://user-images.githubusercontent.com/7807586/155321052-217f429f-f7ae-4e3c-9774-d084aa52f3c5.png)

I completely removed the dnd5e system, restarted foundry, reinstalled the 5e system and i get the error above.

I don't truly believe its a hosting error. Everything is accessible to over 65 other installed modules, its just this one throwing problems.

**Comment by hematic** [comment]
Maybe its looking in the wrong place? I mean my foundry url is only partly correct in that get request.

https://home.phillipmarshall.us/foundry would be the correct URL

The file does exist.

![image](https://user-images.githubusercontent.com/7807586/155322179-e7ecf9bc-9a5b-4593-b11f-52da5cff7ea5.png)

**Comment by DanielBoettner** [comment]
This seems to be an issue with your hosting.

I can try to find a solution. Likely just going up the directories instead of starting from the root.

But however this hosting is done. The web is likely not correctly configured.
`/systems` tells the script to look for `systems` directory at the web root directory.

For some reason foundry itself is placed in a subdirectory.
But it seems, as described above, this is not properly set as a web root.
This is the same reason as why likely the background image of your login page does not show up.

Either way, I will try to patch how the import happens. This should not occur again in the next update.

Still, for you I recommend either
* creating a subdomain instead of a subdirectory.
  *  so / always shows to the root of the subdomain
   
* checking out how to set the web root and public root.
depends on your webserver

**Comment by DanielBoettner** [comment]
Should be fixed in version 3.5.10

**Comment by hematic** [comment]
Can confirm this did fix my issue. I will look into the other things you mentioned. Thanks very much for the prompt help!
