### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by lucaspsilva90** [jopeek/fvtt-loot-sheet-npc-5e#330]
Can't install it from Foundry  module installer.

using 8.9 version at ubuntu

![image](https://user-images.githubusercontent.com/54728894/162043788-d460ec5d-5f3f-4609-9bb3-5fad68dca51d.png)

**Comment by DanielBoettner** [comment]
For Foundry 0.8 the last version was https://github.com/jopeek/fvtt-loot-sheet-npc-5e/releases/tag/v3.2.5.
Could be that the manifest installation wont work (currently) as the link in the error should point to the v9 version.

You can try to download the release zip manually and install it by uploading it.
Otherwise I have to ask you for patience. Or I recommend upgrading Foundry to v9.
