### ISSUE TITLE
Purchase conversion not working

### ISSUE THREAD

**Issue by Dreimell** [jopeek/fvtt-loot-sheet-npc-5e#430]
**Describe the bug**
when a player buys an item for 1 copper coin, and the player has 1 silver coin on him, the item is purchased but the player still has 1 Silver coin, the regular text in chat comes "player purchases 1x item for 1cp" but on gm screen a n error pops up. but if the layer has 1 copper coin on him, the puchase works perfectly.

**To Reproduce**
1. Go to 'merchant character sheet'
2. Click on 'buy item'
3. Scroll down in chat you see the transaction
4. See error.

**Expected behavior**
used to make conversions with purchases.

**Screenshots**
![image](https://github.com/user-attachments/assets/95504ab6-4bb6-4889-8139-dafe3d1380cb)

**Desktop (please complete the following information):**
 - OS: win 11 pro
 - Browser: chrome
 - Versions : foundry 12.331      d&d 3.3.1        Loot sheet NPC 5e (simple version) 12.400.7

**Comment by jopeek** [comment]
Strange. I cannot reproduce that. I've identified one or two different bugs while trying though...
- buyer has exactly 1 copper but cannot purchase item for 1 copper 
- merchant doesn't get proper change when buyer purchases item for 1 copper but pays in 1 silver.

**Comment by jopeek** [comment]
Yeah, I can't reproduce that. I tried several times.

I have a player with 1 silver coin and nothing else. That player then buys an item for 1 copper. The result is the player ends up with 9 copper pieces and the item. The merchant ends up with the 1 silver piece and 9 less copper (change given to player). There is a minor bug where if the merchant does not have 9 copper to give, it'll just do it anyway. I think that's fine because nobody really cares if the merchant has the change available, imho.
